# Mybatis && 通用 Mapper && 分页工具
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
mapper:
  mappers:
  - com.jucheng.ruby.mapper.BaseCrudMapper
  identity: MYSQL
pagehelper:
  auto-dialect: true
  close-conn: true
 
# Ribbon配置信息
ribbon:
  # 超时时间,单位:毫秒
  ConnectTimeout: 5000
  ReadTimeout: 30000
  # 默认重试机制(只对GET请求进行重试)
  # 对当前实例的重试次数
  MaxAutoRetries: 0
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: false
  # 饥饿加载
  eager-load:
    enabled: true
    #clients:
    #- mercury

# Feign配置信息
feign:
  client:
    config:
      # 设置全局日志级别
      default:
        # Feign客户端默认的Logger.Level对象定义为NONE级别，不会记录任何Fegin调用过程中的信息
        loggerLevel: full
  # 开启熔断
  hystrix:
    enabled: true

hystrix:
  command:
    # 默认超时时间,建议"Hystrix超时 > Ribbon超时",否则将可能导致重试特性失效
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 31000

# 日志配置
logging:
  level:
    com.geeorange.neptune.auth.dao: DEBUG            
# ES日志推送配置
management:
  health:
    elasticsearch:
      enabled: false
